version: '3.7'

python-code-challenge:
  web:
    build: ./web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev